// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6NIy9-k-jvhyj6vuieEg1Q4nJSr25eCY',
    appId: '1:543226553618:web:0a0347456ba0b49fd5bfcb',
    messagingSenderId: '543226553618',
    projectId: 'prova-98729',
    authDomain: 'prova-98729.firebaseapp.com',
    databaseURL: 'https://prova-98729-default-rtdb.firebaseio.com',
    storageBucket: 'prova-98729.firebasestorage.app',
    measurementId: 'G-LKT75JV54M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAda73M9vBMkUlKMZ3xnaxNZiWHlbXlFNo',
    appId: '1:543226553618:android:9007a25ac5fa0b06d5bfcb',
    messagingSenderId: '543226553618',
    projectId: 'prova-98729',
    databaseURL: 'https://prova-98729-default-rtdb.firebaseio.com',
    storageBucket: 'prova-98729.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6NIy9-k-jvhyj6vuieEg1Q4nJSr25eCY',
    appId: '1:543226553618:web:c7cfa93264e503a5d5bfcb',
    messagingSenderId: '543226553618',
    projectId: 'prova-98729',
    authDomain: 'prova-98729.firebaseapp.com',
    databaseURL: 'https://prova-98729-default-rtdb.firebaseio.com',
    storageBucket: 'prova-98729.firebasestorage.app',
    measurementId: 'G-B4YNGVCYT8',
  );
}
